# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coe8xy7y1IX509DjhrvEYaSPYhJf6pPx

# f string in python
"""

age = 19

my_intro = f" my name  ids atul kumar shahi and i am  { age } year old "

print(my_intro)

"""# conditional statement in python


"""

if age > 18 :
   print("you are eegeble for drive this car and  not eligible for  driftng " )

gender = input("enter your gender : ")
if age >18 and gender == "male" :
  print(" you do what you want to do ")
else :
  print("you are not eligible for drive this car ")

gender = input("enter your gender : ")
if age >18 and gender == "male" :
  print(" you do what you want to do ")
elif gender == "female":
  print("you are  allow to drive but donot do drift

   " )
else :
  print("you are not eligible for drive this car ")

"""# function in python

"""

def sum(q,w):
  return  q+w;

sum(5,9
    )

"""# loop in python"""

for i in range(10):
  print(i)

name = "atul kumar shahi"  ## print the char of a string


for char in name:
  print(char)

for i in range(1 , 100 , 10):
  print(i)

roll_numbers = [1,85,8,8,88,78,5,58,5,85,4,4,58,56,51,2,41,4,45,5,5]

for i in roll_numbers:
  print(i)

"""# while loop"""

while roll_numbers:
  print(roll_numbers.pop())